name: Features
on:
  push:
    branches:
    - feature/**
    - hotfix/**
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-php.yml@master
    with:
      PHP_VERSION: 8.1
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    needs: 
    - build
    uses: bayudwiyansatria/.github/.github/workflows/test-php.yml@master
    with:
      PHP_VERSION: 8.1
      ARTIFACT_REPOSITORY: ${{ github.repository }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
