name: Main
on:
  push:
    branches:
    - master
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-php.yml@master
    with:
      PHP_VERSION: 8.1
      PHP_BUILD_COMMAND: composer run build:ci
      NODE_VERSION: 21
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    needs: 
    - build
    uses: bayudwiyansatria/.github/.github/workflows/test-php.yml@master
    with:
      PHP_VERSION: 8.1
      PHP_BUILD_COMMAND: composer run build:ci
      TEST_SKIP_CODECOV: true
    secrets:
      CODECOV_TOKEN: null
  